title: J.T. James
email: joeltjames@gmail.com
description: >-
  A Personal Page for J.T. James
baseurl: ""
url: ""
github_username: joeltjames

# Build settings
markdown: kramdown
theme: minimal-mistakes-jekyll
minimal_mistakes_skin: "dark" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"
plugins:
  - jekyll-include-cache

author:
  name: "J.T. James"
  avatar: "/assets/images/headshot.jpg"
  bio: "A senior software engineer with a passion for improving efficiency, solving complex problems, and fiddling with sports data."
  location: "Georgia, USA"
  links:
    - label: "joeltjames.com"
      icon: "fas fa-fw fa-link"
      url: "https://joeltjames.com"
defaults:
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
  # _projects
  - scope:
      path: ""
      type: projects
    values:
      layout: single
      author_profile: false
      share: true
collections:
  projects:
    output: true
    permalink: /:collection/:path/

include: ["_pages"]